<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY8EOxbZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY8EOxbZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY8EOxbZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY8EOxbZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY8EOxbZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y8EOxbZ',
    'container.build_id' => '4144d1a3',
    'container.build_time' => 1641210053,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY8EOxbZ');
