<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI4yf7yD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI4yf7yD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI4yf7yD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI4yf7yD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI4yf7yD\App_KernelDevDebugContainer([
    'container.build_hash' => 'I4yf7yD',
    'container.build_id' => '3d557edb',
    'container.build_time' => 1638982684,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI4yf7yD');
